app/models.py
from app import db
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy import String, Date, ForeignKey, Integer
from datetime import date
from flask_login import UserMixin
from typing import List

#------Users table------
class User(db.Model, UserMixin):
    __tablename__ = "user_account"

    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str] = mapped_column(String(30))
    password_hash: Mapped[str] = mapped_column(nullable=False)

    tasks: Mapped[List["Task"]] = relationship(back_populates="user")

    def set_password(self, password: str):
        from werkzeug.security import generate_password_hash
        self.password_hash = generate_password_hash(password)

    def check_password(self, password: str) -> bool:
        from werkzeug.security import check_password_hash
        return check_password_hash(self.password_hash, password)
    
    def __repr__(self):
        return f'User(id={self.id!r}, name={self.name!r})'
    
#------Tasks table------
class Task(db.Model):
    __tablename__ = "task"

    id: Mapped[int] = mapped_column(primary_key=True)
    title: Mapped[str] = mapped_column(String(40))
    description: Mapped[str] = mapped_column(String(255), nullable=True)
    due_date: Mapped[date] = mapped_column(Date, nullable=True)
    priority: Mapped[int] = mapped_column(Integer, nullable=False)
    status: Mapped[str] = mapped_column(String(15))
    user_id: Mapped[int] = mapped_column(ForeignKey("user_account.id"), nullable=False)  

    user: Mapped["User"] = relationship(back_populates="tasks")

    @property
    def priority_label(self):
        PRIORITY_MAP = {1: "Very Low", 2: "Low", 3: "Medium", 4: "High", 5:"Urgent"}
        return PRIORITY_MAP.get(self.priority, "Unknown")
    
    @property
    def status_label(self):
        STATUS_MAP = {"todo": "To Do", "in_progress": "In Progress", "done": "Done"}
        return STATUS_MAP.get(self.status, "Unknown")

    def __repr__(self):
        return f'Task(id={self.id!r}, title={self.title!r}, description={self.description!r}, due_date={self.due_date!r}, priority={self.priority!r}, status={self.status!r})'

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField, DateField, SelectField, TextAreaField
from wtforms.validators import InputRequired, EqualTo, Optional

class AddATask(FlaskForm):
    title = StringField("Title:", validators=[InputRequired()])
    description = TextAreaField("Descriptiton:", validators=[Optional()])
    due_date = DateField("Due Date:", validators=[Optional()])
    priority = SelectField(
        "Priority",
        choices=[
            ("1", "Very Low"),
            ("2", "Low"),
            ("3", "Medium"),
            ("4", "High"),
            ("5", "Urgent")
        ],
        default="3"
    )
    status = SelectField(
        "Status",
        choices=[
            ("todo", "To Do"),
            ("in_progress", "In Progress"),
            ("done", "Done")
        ],
        default="todo"
    )
    submit = SubmitField("Submit")

class RegistrationForm(FlaskForm):
    name = StringField("Username", validators=[InputRequired()])
    password = PasswordField("Password", validators=[InputRequired()])
    password2 = PasswordField("Repeat Password", validators=[InputRequired(), EqualTo("password")])
    submit = SubmitField("Register")

class LoginForm(FlaskForm):
    name = StringField("Username", validators=[InputRequired()])
    password = PasswordField("Password", validators=[InputRequired()])
    submit = SubmitField("Log in")

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager

db = SQLAlchemy()
migrate = Migrate()
login_manager = LoginManager()

def create_app():
    app = Flask(__name__, template_folder='templates', static_folder='static')

    # config setup
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///task_manage.db'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    app.config['SECRET_KEY'] = 'secret-key'

    # initialize extensions
    db.init_app(app)
    migrate.init_app(app, db)
    login_manager.init_app(app)

    from .models import User

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int((user_id)))

    from .routes import register_routes
    register_routes(app)

    return app

app/routes/__init__.py
from .task_routes import task_bp
from .auth_routes import auth_bp

def register_routes(app):
    app.register_blueprint(task_bp)
    app.register_blueprint(auth_bp)

app/routes/auth_routes.py
from flask import Blueprint, render_template, redirect, flash, url_for, request, session
from ..forms import LoginForm, RegistrationForm
from ..models import User
from app import db
from sqlalchemy import select
from flask_login import login_user, logout_user, login_required, current_user

auth_bp = Blueprint('auth', __name__)

@auth_bp.route("/register", methods=["GET", "POST"])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        stmt = select(User).where(User.name == form.name.data)
        existing_user = db.session.scalars(stmt).one_or_none()
        if existing_user:
            form.name.errors.append("Username already taken.")
        else:
            user = User(name=form.name.data)
            user.set_password(form.password.data)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for("auth.login"))

    return render_template("register.html", form=form)

@auth_bp.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        stmt = select(User).where(User.name == form.name.data)
        user = db.session.scalars(stmt).one_or_none()
        if user and user.check_password(form.password.data):
            login_user(user)
            return redirect(url_for("task.index"))
        else:
            flash("Invalid username or password.", "error")
    return render_template("login.html", form=form)

@auth_bp.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("auth.login"))

#-----DELETE USER------
# @auth_bp.route("/delete_user/<username>", methods=["GET"])
# def delete_user(username):
#     stmt = select(User).where(User.name == username)
#     users = db.session.scalars(stmt).all()

#     if not users:
#         flash("User not found.", "error")
#     else:
#         for user in users:
#             db.session.delete(user)
#         db.session.commit()
#         flash(f"Deleted {len(users)} user(s) with the name '{username}'.", "success")

#     return redirect(url_for("auth.register"))  # or any appropriate page

app/routes/task_routes.py
from flask import Blueprint, render_template, redirect, url_for, session, request, abort
from ..forms import AddATask  # relative import
from flask_login import current_user, login_required
from ..models import Task, User
from app import db
from sqlalchemy import select

task_bp = Blueprint('task', __name__)

@task_bp.route('/')
def index():
    return render_template("index.html")

@task_bp.route('/tasks', methods=["GET", "POST"])
@login_required
def task_management():
    form = AddATask()
    if form.validate_on_submit():
        new_task = Task(
            title=form.title.data,
            description=form.description.data,
            due_date=form.due_date.data,
            priority=int(form.priority.data),
            status=form.status.data,
            user_id=current_user.id
        )
        db.session.add(new_task)
        db.session.commit()
        return redirect(url_for("task.task_management"))
    
    stmt = select(Task).join(Task.user).order_by(Task.due_date.asc()).where(User.name == current_user.name)
    tasks = db.session.scalars(stmt).all()    

    return render_template("task_management.html", form=form, tasks=tasks)

@task_bp.route('/edit/<int:task_id>', methods=["GET", "POST"])
@login_required
def edit_task(task_id):
    task = Task.query.get_or_404(task_id)

    if task.user_id != current_user.id:
        abort(403)

    form = AddATask(obj=task)

    if form.validate_on_submit():
        form.populate_obj(task)
        db.session.commit()
        return redirect(url_for('task.task_management'))
    
    return render_template('edit_task.html', form=form, task=task)

@task_bp.route('/delete/<int:task_id>', methods=["POST"])
@login_required
def delete_task(task_id):
    task = Task.query.get_or_404(task_id)
    db.session.delete(task)
    db.session.commit()
    return redirect(url_for('task.task_management'))

app/templates/base.html
<!DOCTYPE>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Task Manager</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}" />
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Rubik:ital,wght@0,300..900;1,300..900&family=Work+Sans:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    </head>
    <body class="bg-background">
        <header class="bg-white border-b border-border px-6 py-4 flex items-center justify-between">
            <!-- Flex container -->
                <h1 class="text-2xl font-bold"><a href="{{ url_for('task.index') }}">Task Manager</a></h1>
                {% if current_user.is_authenticated %}
                    <nav>
                        <ul class="flex space-x-6 text-center">
                            <div class="flex space-x-1">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                                    <path stroke-linecap="round" stroke-linejoin="round" d="M17.982 18.725A7.488 7.488 0 0 0 12 15.75a7.488 7.488 0 0 0-5.982 2.975m11.963 0a9 9 0 1 0-11.963 0m11.963 0A8.966 8.966 0 0 1 12 21a8.966 8.966 0 0 1-5.982-2.275M15 9.75a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" />
                                </svg>

                                <li>{{ current_user.name }}</li>
                            </div>
                            <li><a href="{{ url_for('auth.logout') }}" class="text-text-secondary hover:text-danger font-medium">Logout</a></li>
                        </ul>
                    </nav>
                {% else %}
                    <nav>
                        <ul class="flex space-x-4 text-center">
                            <li><a href="{{ url_for('auth.register') }}" class="text-text-secondary hover:text-primary font-medium">Register</a></li>
                            <li><a href="{{ url_for('auth.login') }}" class="text-text-secondary hover:text-primary font-medium">Login</a></li>
                        </ul>
                    </nav>
                {% endif %}
        </header>
        <main class="content mx-auto">
            {% block main_content %}{% endblock %}
        </main>
    </body>
</html>

app/templates/edit_task.html
{% extends "base.html" %}

{% block main_content %}
    <section class="max-w-2xl mx-auto md:bg-card p-6 md:rounded-lg md:shadow-md m-10">
        <h2 class="text-2xl font-semibold mb-6 text-text-primary">Edit</h2>
        <form action="" method="POST" class="space-y-4">
            {{ form.hidden_tag() }}
            <!-- Title -->
            <div>
                {{ form.title.label(class="block text-sm font-medium text-text-secondary mb-1") }}
                {{ form.title(class="w-full p-2 border border-border rounded focus:outline-none focus:ring-2 focus:ring-primary") }}
                {% for error in form.title.errors %}
                    <p class="text-sm text-danger mt-1">{{ error }}</p>
                {% endfor %}
            </div>
            <!-- Description -->
             <div>
                {{ form.description.label(class="block text-sm font-medium text-text-secondary mb-1") }}
                {{ form.description(class="w-full p-2 border border-border rounded focus:outline-none focus:ring-2 focus:ring-primary") }}
            </div>
            <!-- Due Date -->
             <div>
                {{ form.due_date.label(class="block text-sm font-medium text-text-secondary mb-1") }}
                {{ form.due_date(class="w-full p-2 border border-border rounded focus:outline-none focus:ring-2 focus:ring-primary") }}
            </div>
            <!-- Priority -->
             <div>
                {{ form.priority.label(class="block text-sm font-medium text-text-secondary mb-1") }}
                {{ form.priority(class="w-full p-2 border border-border rounded focus:outline-none focus:ring-2 focus:ring-primary") }}
            </div>
            <!-- Status -->
             <div>
                {{ form.status.label(class="block text-sm font-medium text-text-secondary mb-1") }}
                {{ form.status(class="w-full p-2 border border-border rounded focus:outline-none focus:ring-2 focus:ring-primary") }}
            </div>
            {{ form.submit(class="py-2 px-4 bg-primary text-background rounded hover:bg-primary-dark transition") }}
        </form>
    </section>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block main_content %}
    {% if current_user.is_authenticated %}
        <div class="container mx-auto text-center m-10">
            <h1 class="text-center text-2xl">Hello, {{ current_user.name }}!</h1>
            <p class="m-5">Create and view tasks below!</p>
            <a href="{{ url_for('task.task_management') }}" class="p-3 bg-primary text-background rounded-full hover:bg-primary-dark transition">Your Tasks</a>
        </div>
    {% else %}
        <div class="container mx-auto text-center my-10">
            <p class="m-5">Please log in if you want to create tasks</p>
            <a href="{{ url_for('auth.login') }}" class="m-3 p-3 bg-primary text-background rounded-full hover:bg-primary-dark transition">Login</a>
            <a href="{{ url_for('auth.register') }}" class="m-3 p-3 text-primary rounded-full border border-transparent hover:border hover:border-primary transition">Register</a>
        </div>
    {% endif %}
{% endblock %}

app/templates/login.html
{% extends "base.html" %}

{% block main_content %}
    <section class="max-w-2xl mx-auto mt-10">
        <h1 class="text-2xl font-semibold mb-6 text-text-primary text-center">Login</h1>
        <form action="" method="POST" class="space-y-4">
            {{ form.hidden_tag() }}
            <div>
            {{ form.name.label(class="block text-sm font-medium text-text-secondary mb-1") }}
            {{ form.name(class="w-full p-2 border border-border rounded focus:outline-none focus:ring-2 focus:ring-primary") }}
            {% for error in form.name.errors %}
                <p class="text-sm text-danger mt-1">{{ error }}</p>
            {% endfor %}
            </div>
            <div>
            {{ form.password.label(class="block text-sm font-medium text-text-secondary mb-1") }}
            {{ form.password(class="w-full p-2 border border-border rounded focus:outline-none focus:ring-2 focus:ring-primary") }}
            {% for error in form.password.errors %}
                <p class="text-sm text-danger mt-1">{{ error }}</p>
            {% endfor %}
            </div>
            {{ form.submit(class="py-2 px-4 bg-primary text-background rounded hover:bg-primary-dark transition") }}
        </form>
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                <ul class="flashes">
                    {% for message in messages %}
                        <li class="text-sm text-danger mt-1">{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        {% endwith %}

    </section>
{% endblock %}

app/templates/register.html
{% extends "base.html" %}

{% block main_content %}
    <section class="max-w-2xl mx-auto mt-10">
        <h1 class="text-2xl font-semibold mb-6 text-text-primary text-center">Register</h1>
        <form action="" method="POST" class="space-y-4">
            {{ form.hidden_tag() }}
            <div>
                {{ form.name.label(class="block text-sm font-medium text-text-secondary mb-1") }}
                {{ form.name(class="w-full p-2 border border-border rounded focus:outline-none focus:ring-2 focus:ring-primary") }}
                {% for error in form.name.errors %}
                    <p class="text-sm text-danger mt-1">{{ error }}</p>
                {% endfor %}
            </div>
                {{ form.password.label(class="block text-sm font-medium text-text-secondary mb-1") }}
                {{ form.password(class="w-full p-2 border border-border rounded focus:outline-none focus:ring-2 focus:ring-primary") }}
                {% for error in form.password.errors %}
                    <p class="text-sm text-danger mt-1">{{ error }}</p>
                {% endfor %}
            <div>
                {{ form.password2.label(class="block text-sm font-medium text-text-secondary mb-1") }}
                {{ form.password2(class="w-full p-2 border border-border rounded focus:outline-none focus:ring-2 focus:ring-primary") }}
                {% for error in form.password2.errors %}
                    <p class="text-sm text-danger mt-1">{{ error }}</p>
                {% endfor %}
            </div>
            {{ form.submit(class="py-2 px-4 bg-primary text-background rounded hover:bg-primary-dark transition") }}
        </form>
    </section>

{% endblock %}

app/templates/task_management.html
{% extends "base.html" %}

{% block main_content %}
    <section class="max-w-2xl mx-auto md:bg-card p-6 md:rounded-lg md:shadow-md m-10">
        <h2 class="text-2xl font-semibold mb-6 text-text-primary">Create a Task</h2>
        <form action="" method="POST" class="space-y-4">
            {{ form.hidden_tag() }}
            <!-- Title -->
            <div>
                {{ form.title.label(class="block text-sm font-medium text-text-secondary mb-1") }}
                {{ form.title(class="w-full p-2 border border-border rounded focus:outline-none focus:ring-2 focus:ring-primary") }}
                {% for error in form.title.errors %}
                    <p class="text-sm text-danger mt-1">{{ error }}</p>
                {% endfor %}
            </div>
            <!-- Description -->
             <div>
                {{ form.description.label(class="block text-sm font-medium text-text-secondary mb-1") }}
                {{ form.description(class="w-full p-2 border border-border rounded focus:outline-none focus:ring-2 focus:ring-primary") }}
            </div>
            <!-- Due Date -->
             <div>
                {{ form.due_date.label(class="block text-sm font-medium text-text-secondary mb-1") }}
                {{ form.due_date(class="w-full p-2 border border-border rounded focus:outline-none focus:ring-2 focus:ring-primary") }}
            </div>
            <!-- Priority -->
             <div>
                {{ form.priority.label(class="block text-sm font-medium text-text-secondary mb-1") }}
                {{ form.priority(class="w-full p-2 border border-border rounded focus:outline-none focus:ring-2 focus:ring-primary") }}
            </div>
            <!-- Status -->
             <div>
                {{ form.status.label(class="block text-sm font-medium text-text-secondary mb-1") }}
                {{ form.status(class="w-full p-2 border border-border rounded focus:outline-none focus:ring-2 focus:ring-primary") }}
            </div>
            {{ form.submit(class="py-2 px-4 bg-primary text-background rounded hover:bg-primary-dark transition") }}
        </form>
    </section>

    
<section class="grid grid-cols-1 md:grid-cols-3 gap-6 mt-8 mx-4">
  {% for status in ['To Do', 'In Progress', 'Done'] %}
    <div class="bg-gray-50 rounded-lg p-4 border border-border shadow">
      <h3 class="text-lg font-bold mb-4">{{ status }}</h3>
      <div class="space-y-4">
        {% for task in tasks if task.status_label == status %}
          <div class="bg-white p-3 rounded shadow border border-border">
            <div class="flex justify-between">
                <h4 class="text-md font-medium">{{ task.title }}</h4>
                <span class="
                px-2 py-1 text-xs font-medium rounded-full
                {% if task.priority_label == 'Urgent' %}
                    bg-red-100 text-red-800 border border-red-300
                {% elif task.priority_label == 'High' %}
                    bg-orange-100 text-orange-800 border border-orange-300	
                {% elif task.priority_label == 'Medium' %}
                    bg-yellow-100	text-yellow-800	border border-yellow-300	
                {% elif task.priority_label == 'Low' %}
                    bg-green-100 text-green-800 border border-green-300	
                {% elif task.priority_label == 'Very Low' %}
                    bg-gray-100	text-gray-800 border border-gray-300	
                {% endif %}
                ">
                    {{ task.priority_label }}
                </span>
            </div>
            <p class="text-sm text-text-secondary">Due: {{ task.due_date }}</p>
            <p class="text-sm">{{ task.description }}</p>
            <div class="flex justify-between text-sm mt-2">
              <a href="{{ url_for('task.edit_task', task_id=task.id) }}" class="text-primary hover:underline">Edit</a>
              <form action="{{ url_for('task.delete_task', task_id=task.id) }}" method="POST">
                <button type="submit" class="text-red-500 hover:underline">Delete</button>
              </form>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  {% endfor %}
</section>
{% endblock %}

templates/base.html
<!DOCTYPE>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>Task Manager</title>
        <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}" />
    </head>
    <body>
        <header>

        </header>
        <main>
            {% block main_content %}{% endblock %}
        </main>
    </body>
</html>